membaman/fees/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

from . import views

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='fees/fees-index.html'), name='feesindex'),
    url(r'^income-list/', views.IncomeListView.as_view(), name='income-list'),
    url(r'^income-list-subyear/', views.IncomeListSubYearView.as_view(), name='income-list-subyear'),
)

membaman/membaman/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.views.generic.base import TemplateView
admin.site.site_header = 'MembaMan Administration Area'
admin.site.site_title = 'MembaMan Admin'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'membaman.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^$', RedirectView.as_view(url='/fees/')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^fees/', include('fees.urls', namespace="fees")),
    url(r'^members/', include('members.urls', namespace="members")),
    url(r'^membaman/', include('membaman.urls', namespace="membaman")),
    url(r'^feedback', include('feedback.urls')),
)

membaman/members/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

from . import views

'''
urlpatterns = patterns('',
    url(r'^$', views.IncomeListView.as_view(), name='income-list'),
)
'''
urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='members/members-index.html'), name='membersindex'),
    url(r'^member-list/', views.MemberActiveListView.as_view(), name='member-list'),
    url(r'^member-nomore-list/', views.MemberNotActiveListView.as_view(), name='member-nomore-list'),
    url(r'^member-view/(?P<pk>\d+)/$', views.MemberDetail.as_view(), name='member-view'),
    url(r'^member-family-finance-list/', views.FamilyFinanceListView.as_view(), name='member-family-finance-list'),
    url(r'^member-debtors-list/', views.MemberDebtorsListView.as_view(), name='member-debtors-list'),
    url(r'^member-finance-list/', views.MemberFinanceListView.as_view(), name='member-finance-list'),
    url(r'^family-view/(?P<pk>\d+)/$', views.FamilyDetail.as_view(), name='family-view'),
)

membaman/members/models.py
from django.db import models

class Organisation(models.Model):
    '''
    An `Organisation` is an entity to which
    `Member` belong
    '''
    class Meta:
        ordering = ['name']

    name = models.CharField(max_length=50)
    postal_address = models.CharField(max_length=150, null=True, blank=True)
    bank_account_name = models.CharField(max_length=100, null=True, blank=True)
    bank_account_number = models.CharField(max_length=50, null=True, blank=True)
    treasurer_name = models.CharField(max_length=50, null=True, blank=True)
    treasurer_phone = models.CharField(max_length=50, null=True, blank=True)
    treasurer_email = models.CharField(max_length=50, null=True, blank=True)
    leader_name = models.CharField(max_length=50, null=True, blank=True)
    leader_phone = models.CharField(max_length=50, null=True, blank=True)
    leader_email = models.CharField(max_length=50, null=True, blank=True)


    def __unicode__(self):
        return unicode(self.name)

class SubOrganisation(models.Model):
    '''
    A `SubOrganisation` is grouping within an
    `Organisation` to which a `Member` primarily
    identifies
    '''
    class Meta:
        ordering = ['sub_name']

    sub_name = models.CharField(max_length=50)
    organisation = models.ForeignKey(Organisation)

    def organisation_name(self):
        return self.organisation.name
    organisation_name.short_description = 'Organisation Name'

    def __unicode__(self):
        return unicode(self.sub_name) + unicode(' (') + unicode(self.organisation.name) + unicode(')')

class Family(models.Model):
    '''
    `Family` constitutes one or more `Caregiver` and one or
    more `Member`
    '''
    class Meta:
        ordering = ['street_address', 'suburb', 'city']

    street_address = models.CharField(max_length=75)
    suburb = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    phone_fixed = models.CharField(max_length=20)

    def __unicode__(self):
        return u', '.join((unicode(self.street_address), unicode(self.suburb), unicode(self.city)))

class Person(models.Model):
    '''
    `Person` is an abstract Model to accomodate personal
    identity
    '''
    class Meta:
        abstract = True

    name_given = models.CharField('given name', max_length=50)
    name_family = models.CharField('family name', max_length=50)

class Caregiver(Person):
    '''
    `Caregiver` is someone who cares for a `Member`
    '''
    class Meta:
        ordering = ['name_family', 'name_given']

    MOTHER = 'MO'
    FATHER = 'FA'
    GRANDMOTHER = 'GM'
    GRANDFATHER = 'GF'
    SIBLING = 'SI'
    OTHER = 'OT'
    RELATIONSHIP_TYPE_CHOICES = (
        (MOTHER, 'Mother'),
        (FATHER, 'Father'),
        (GRANDMOTHER, 'Grandmother'),
        (GRANDFATHER, 'Grandfather'),
        (SIBLING, 'Sibling'),
        (OTHER, 'Other'),
    )

    family = models.ForeignKey(Family)
    phone_mobile = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    relationship = models.CharField(max_length=2,
                                    choices=RELATIONSHIP_TYPE_CHOICES,
                                    default=OTHER)

    def __unicode__(self):
        return u', '.join((unicode(self.name_family), unicode(self.name_given)))

class Member(Person):
    '''
    `Member` is a `Person` who directly participates in an `Organisation`
    '''
    class Meta:
        ordering = ['name_family', 'name_given']

    KEA = 'KE'
    CUB = 'CU'
    SCOUT = 'SC'
    VENTURER = 'VE'
    UNKNOWN = 'UK'
    MEMBERSHIP_TYPE_CHOICES = (
        (KEA, 'Kea'),
        (CUB, 'Cub'),
        (SCOUT, 'Scout'),
        (VENTURER, 'Venturer'),
        (UNKNOWN, 'Unknown'),
    )
    organisation = models.ForeignKey(Organisation)
    sub_organisation = models.ForeignKey(SubOrganisation)
    membership_type = models.CharField(max_length=2,
                                       choices=MEMBERSHIP_TYPE_CHOICES,
                                       default=UNKNOWN)
    family = models.ForeignKey(Family)
    primary_caregiver = models.ForeignKey(Caregiver, related_name='primary_caregiver')
    caregivers = models.ManyToManyField(Caregiver, related_name='caregivers')
    date_of_birth = models.DateField(null=True, blank=True)
    date_invested = models.DateField(null=True, blank=True)
    no_longer_attends = models.BooleanField(default=False)
    no_longer_attends_notification = models.DateField(null=True, blank=True)

    def __unicode__(self):
        '''
        Returns "Smith, John"
        '''
        return u', '.join((unicode(self.name_family), unicode(self.name_given)))

    def last_first_name(self):
        '''
        Returns "Smith, John"
        '''
        return u', '.join((unicode(self.name_family), unicode(self.name_given)))

    def first_last_name(self):
        '''
        Returns "John Smith"
        '''
        return u' '.join((unicode(self.name_given), unicode(self.name_family)))

    def first_last_name_memtype_desc(self):
        '''
        Returns "John Smith (Scout)"
        '''
        out = self.first_last_name()
        if self.membership_type == self.UNKNOWN:
            pass
        else:
            for mem_type_tuple in self.MEMBERSHIP_TYPE_CHOICES:
                if mem_type_tuple[0] == self.membership_type:
                    outfull = u"%s (%s)" % (out, unicode(mem_type_tuple[1]))
                    out = outfull
                    break
        return out

    def primary_caregiver_email(self):
        return unicode(self.primary_caregiver.email)

membaman/members/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, UpdateView

from django.core.urlresolvers import reverse
from django.db.models import Count, Sum, F
from .models import Family, Caregiver, Member, Person 

TEMP_ORG_NAME = 'Conversion Group'
TEMP_ORG_ID = 45 

class MemberDetail(DetailView):
    model = Member
    context_object_name = "member_detail"

class MemberDebtorsListView(ListView):
    model = Member
    template_name = 'members/member_debtors_list.html'
    context_object_name = "member_list"
    paginate_by = 100

    def get_queryset(self):

        #The last 'exclude' in the following filter seems to be excluding rows which
        #should not be excluded. I'm not sure what it was there for in the first place
        #or the full effect of removing it but it's certainly the case that there are
        #people who owe money who won't appear in the output if that exclude is in place
        #
        #Update: I think the problem are those people who've never paid anything . Those
        #people are excluded via that exclude and that is not a good idea.
        mem = Member.objects.filter(no_longer_attends=False)\
                            .annotate(debt_total=Sum('accountentry__accountdebt__amount'))\
                            .annotate(payment_total=Sum('accountentry__accountpayment__amount'))\
                            .annotate(debt=Sum('accountentry__accountpayment__amount'))\
                            .filter(debt_total__gt=0)\
                            .exclude(payment_total__gte=F('debt_total'))

        mem = Member.objects.filter(no_longer_attends=False)\
                            .annotate(debt_total=Sum('accountentry__accountdebt__amount'))\
                            .annotate(payment_total=Sum('accountentry__accountpayment__amount'))\
                            .annotate(debt=Sum('accountentry__accountpayment__amount'))\
                            .filter(debt_total__gt=0)

        return mem

class MemberFinanceListView(ListView):
    model = Member
    template_name = 'members/member_finance_list.html'
    context_object_name = "member_list"
    paginate_by = 100

    def get_queryset(self):

        mem = Member.objects.filter(no_longer_attends=False).annotate(debt_total=Sum('accountentry__accountdebt__amount'), payment_total=Sum('accountentry__accountpayment__amount'))
        return mem

class MemberListView(ListView):
    model = Member
    template_name = 'members/member_list.html'
    context_object_name = "member_list"
    paginate_by = 100

    def get_queryset(self, active):
        mem = Member.objects.filter(no_longer_attends=active)
        return mem


class MemberActiveListView(MemberListView):
    def get_queryset(self):
        return super(MemberActiveListView, self).get_queryset(active=False)


class MemberNotActiveListView(MemberListView):
    def get_queryset(self):
        return super(MemberNotActiveListView, self).get_queryset(active=True)

class FamilyListView(ListView):
    model = Family 
    template_name = 'members/family_list.html'
    context_object_name = "family_list"
    paginate_by = 100

    def get_queryset(self):
        fam = Family.objects.all()
        return fam

class FamilyFinanceListView(FamilyListView):

    def get_queryset(self):
        fam = Family.objects.all().annotate(count_members=Count('member'))

        #return super(FamilyFinanceListView, self)
        return fam

class FamilyDetail(DetailView):
    model = Family
    context_object_name = "family_detail"

membaman/templates/members/family_detail.html
{% load i18n %}


<a href="{% url 'membaman:index' %}">Membaman Home Page</a>|
<a href="{% url 'fees:feesindex' %}">Fees Home Page</a>|
<a href="{% url 'members:membersindex' %}">Members Home Page</a>|

<h2>Family View</h2>
<p>Street Address: {{family_detail.street_address }}</p>
<p>Suburb: {{family_detail.suburb }}</p>
<p>City: {{family_detail.city }}</p>
<p>Phone Fixed: {{family_detail.phone_fixed }}</p>

membaman/templates/members/family_list.html
{% extends "baselist.html" %}
{% load i18n %}

{% block content %}

<a href="{% url 'membaman:index' %}">Membaman Home Page</a>|
<a href="{% url 'fees:feesindex' %}">Fees Home Page</a>|
<a href="{% url 'members:membersindex' %}">Members Home Page</a>|

<style>
  table.bandedtab{
    border-collapse: collapse;
    border: 1px solid black;
  }
  table.bandedtab td, table.bandedtab th{
    border: 1px solid black;
    padding: 10px 20px;
  }
  table.bandedtab td.famon{
    background-color: olive;
  }
  table.bandedtab td.famoff{
    background-color: green;
  }
  
</style>
<h2>Families</h2>

{% if family_list %}
    <table class="bandedtab" id="member">
        <tr>
            <th>Street Address</th>
            <th>Count of Members in Family</th>
        </tr>
        {% for family in family_list %}
            <tr>
                <td class = "famon"><a href="{% url 'members:family-view' family.id %}">{{ family.street_address }}</a></td>
                <td class = "famon">{{ family.count_members }}</td>
            <tr>
        {% endfor %}
    </table>
{% else %}
    <h3>No Families</h3>
    <p>No families found</p>
{% endif %}
{% endblock %}

membaman/templates/members/member_debtors_list.html
{% extends "baselist.html" %}
{% load i18n %}

{% block content %}

<a href="{% url 'membaman:index' %}">Membaman Home Page</a>|
<a href="{% url 'fees:feesindex' %}">Fees Home Page</a>|
<a href="{% url 'members:membersindex' %}">Members Home Page</a>|

<style>
  table.bandedtab{
    border-collapse: collapse;
    border: 1px solid black;
  }
  table.bandedtab td, table.bandedtab th{
    border: 1px solid black;
    padding: 10px 20px;
  }
  table.bandedtab td.famon{
    background-color: olive;
  }
  table.bandedtab td.famoff{
    background-color: green;
  }
  
</style>
<h2>Families</h2>

{% if member_list %}
    <table class="bandedtab" id="member">
        <tr>
            <th>Member</th>
            <th>Debt</th>
            <th>Payments</th>
            <th>Caregivers</th>
            <th>Street Address</th>
        </tr>
        {% for member in member_list %}
            <tr>
                <td class = "famon"><a href="{% url 'members:member-view' member.id %}">{{ member.last_first_name }}</a></td>
                <td class = "famon">{{ member.debt_total}}</td>
                <td class = "famon">{{ member.payment_total}}</td>
                <td class = "famon">{{ member.primary_caregiver}}</td>
                <td class = "famon">{{ member.member}}</td>
            <tr>
        {% endfor %}
    </table>
{% else %}
    <h3>No Families</h3>
    <p>No families found</p>
{% endif %}
{% endblock %}

membaman/templates/members/member_detail.html
{% load i18n %}


<a href="{% url 'membaman:index' %}">Membaman Home Page</a>|
<a href="{% url 'fees:feesindex' %}">Fees Home Page</a>|
<a href="{% url 'members:membersindex' %}">Members Home Page</a>|

<h2>Member View</h2>
<p>Name: {{member_detail.first_last_name }}</p>
<p>Membership Type: {{member_detail.membership_type }}</p>
<p>Primary Caregiver: {{member_detail.primary_caregiver }}</p>
<p>No longer attends ?: {{member_detail.no_longer_attends }}</p>

membaman/templates/members/member_finance_list.html
{% extends "baselist.html" %}
{% load i18n %}

{% block content %}

<a href="{% url 'membaman:index' %}">Membaman Home Page</a>|
<a href="{% url 'fees:feesindex' %}">Fees Home Page</a>|
<a href="{% url 'members:membersindex' %}">Members Home Page</a>|

<style>
  table.bandedtab{
    border-collapse: collapse;
    border: 1px solid black;
  }
  table.bandedtab td, table.bandedtab th{
    border: 1px solid black;
    padding: 10px 20px;
  }
  table.bandedtab td.famon{
    background-color: olive;
  }
  table.bandedtab td.famoff{
    background-color: green;
  }
  
</style>
<h2>Families</h2>

{% if member_list %}
    <table class="bandedtab" id="member">
        <tr>
            <th>Member</th>
            <th>Debt</th>
            <th>Payments</th>
            <th>Caregivers</th>
            <th>Street Address</th>
        </tr>
        {% for member in member_list %}
            <tr>
                <td class = "famon"><a href="{% url 'members:member-view' member.id %}">{{ member.last_first_name }}</a></td>
                <td class = "famon">{{ member.debt_total}}</td>
                <td class = "famon">{{ member.payment_total}}</td>
                <td class = "famon">{{ member.primary_caregiver}}</td>
                <td class = "famon">{{ member.member}}</td>
            <tr>
        {% endfor %}
    </table>
{% else %}
    <h3>No Families</h3>
    <p>No families found</p>
{% endif %}
{% endblock %}

membaman/templates/members/member_list.html
{% extends "baselist.html" %}
{% load i18n %}

{% block content %}

<a href="{% url 'membaman:index' %}">Membaman Home Page</a>|
<a href="{% url 'fees:feesindex' %}">Fees Home Page</a>|
<a href="{% url 'members:membersindex' %}">Members Home Page</a>|

<style>
  table.bandedtab{
    border-collapse: collapse;
    border: 1px solid black;
  }
  table.bandedtab td, table.bandedtab th{
    border: 1px solid black;
    padding: 10px 20px;
  }
  table.bandedtab td.famon{
    background-color: olive;
  }
  table.bandedtab td.famoff{
    background-color: green;
  }
  
</style>
<h2>Families</h2>

{% if member_list %}
    <table class="bandedtab" id="member">
        <tr>
            <th>Member</th>
            <th>Caregivers</th>
            <th>Street Address</th>
        </tr>
        {% for member in member_list %}
            <tr>
                <td class = "famon"><a href="{% url 'members:member-view' member.id %}">{{ member.last_first_name }}</a></td>
                <td class = "famon">{{ member.primary_caregiver}}</td>
                <td class = "famon">{{ member.member}}</td>
            <tr>
        {% endfor %}
    </table>
{% else %}
    <h3>No Families</h3>
    <p>No families found</p>
{% endif %}
{% endblock %}

membaman/templates/members/members-index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<a href="{% url 'membaman:index' %}">Membaman Home Page</a>|
<a href="{% url 'fees:feesindex' %}">Fees Home Page</a>|
<a href="{% url 'members:membersindex' %}">Members Home Page</a>|
<h2>Members Home Page</h2>

<ol>
    <li><a href="{% url 'members:member-list' %}">Member List</a></li>
    <li><a href="{% url 'members:member-finance-list' %}">Member Finance List</a></li>
    <li><a href="{% url 'members:member-nomore-list' %}">Previously Members but now left</a></li>
    <li><a href="{% url 'members:member-family-finance-list' %}">Financial Details by Family </a></li>
    <li><a href="{% url 'members:member-debtors-list' %}">Debtor Details </a></li>
    <li><a href="{% url 'membaman:index' %}">Membaman Home Page</a></li>
</ol>

{% endblock %}