membaman/fees/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

from . import views

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='fees/fees-index.html'), name='feesindex'),
    url(r'^income-list/', views.IncomeListView.as_view(), name='income-list'),
    url(r'^income-list-subyear/', views.IncomeListSubYearView.as_view(), name='income-list-subyear'),
)

membaman/membaman/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.views.generic.base import TemplateView
admin.site.site_header = 'MembaMan Administration Area'
admin.site.site_title = 'MembaMan Admin'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'membaman.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^$', RedirectView.as_view(url='/fees/')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^fees/', include('fees.urls', namespace="fees")),
    url(r'^members/', include('members.urls', namespace="members")),
    url(r'^membaman/', include('membaman.urls', namespace="membaman")),
    url(r'^feedback', include('feedback.urls')),
)

membaman/members/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

from . import views

'''
urlpatterns = patterns('',
    url(r'^$', views.IncomeListView.as_view(), name='income-list'),
)
'''
urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='members/members-index.html'), name='membersindex'),
    url(r'^member-list/', views.MemberActiveListView.as_view(), name='member-list'),
    url(r'^member-nomore-list/', views.MemberNotActiveListView.as_view(), name='member-nomore-list'),
    url(r'^member-view/(?P<pk>\d+)/$', views.MemberDetail.as_view(), name='member-view'),
    url(r'^member-family-finance-list/', views.FamilyFinanceListView.as_view(), name='member-family-finance-list'),
    url(r'^member-debtors-list/', views.MemberDebtorsListView.as_view(), name='member-debtors-list'),
    url(r'^member-finance-list/', views.MemberFinanceListView.as_view(), name='member-finance-list'),
    url(r'^family-view/(?P<pk>\d+)/$', views.FamilyDetail.as_view(), name='family-view'),
)

membaman/fees/models.py
from django.db import models

from members.models import Organisation
from members.models import Member

# Create your models here.
class Year(models.Model):
    '''
    A `Year` models a single year
    of an `Organisation` activity

    '''
    class Meta:
        ordering = ['start', 'end']

    organisation = models.ForeignKey(Organisation)
    name = models.CharField(max_length=20)
    start = models.DateField()
    end = models.DateField()

    def __unicode__(self):
        return unicode(self.name) + unicode(' (') + unicode(self.organisation.name) + unicode(')')

class SubYear(models.Model):
    '''
    A fraction of the `Year` model

    There should be sufficient `SubYear`
    instances with suitable start end
    dates so that the whole year is covered
    with no gaps.

    In some cases a SubYear will be a 1-1
    with Year depending on how the `Organisation`
    does their billing.

    '''
    class Meta:
        ordering = ['year__organisation__name', 'start', 'end']

    year = models.ForeignKey(Year)
    name = models.CharField(max_length=20)
    start = models.DateField()
    end = models.DateField()

    def year_name(self):
        return self.year.name
    year_name.short_description = 'Year Name'

    def organisation_name(self):
        return self.year.organisation
    organisation_name.short_description = 'Organisation Name'

    def __unicode__(self):
        return unicode(self.name) + unicode(' (') + unicode(self.year.organisation.name) + unicode(' - ') + unicode(self.year.name) + unicode(')')

class Income(models.Model):
    '''
    `Income` represents the income from a `Member`
    based for a given `SubYear`

    Initially the model will just be a string
    to contain the non-numeric values that have
    been entered into the data that's being converted
    from but in the longer term this model will take
    on a more typed form
    '''
    class Meta:
        ordering = ['member__name_family', 'member__name_given', 'subyear__start', 'subyear__end']

    subyear = models.ForeignKey(SubYear)
    member = models.ForeignKey(Member)
    received = models.CharField(max_length=100)

    def year_name(self):
        return self.subyear.year.name
    year_name.short_description = 'Year Name'

    def subyear_name(self):
        return self.subyear.name
    subyear_name.short_description = 'Sub-Year Name'

    def __unicode__(self):
        return unicode(' (') + unicode(self.subyear.year.name) + unicode(' - ') + \
            unicode(self.subyear.name) + unicode(':') + unicode(self.member) + \
            unicode(')') + unicode(self.received)

class AccountEntry(models.Model):
    '''
    `AccountEntry` represents either a debt or a
    credit. We record membership payments which 
    have been asked for via `AccountEntry` and we
    record amounts received via `AccountEntry`

    '''
    DEBT = 'DT'
    CREDIT = 'CR'

    ACCOUNT_ENTRY_TYPE_CHOICES = (
        (DEBT, 'Debt'),
        (CREDIT, 'Credit')
    )
    member = models.ForeignKey(Member)
    amount = models.DecimalField(max_digits=5, decimal_places=2)
    date = models.DateField()

class AccountDebt(AccountEntry):
    invoice_reference = models.CharField(max_length=10)

class AccountPayment(AccountEntry):

    AUTOPAYMENT = 'AT'
    BANKTRANSFER = 'TR'
    CASH = 'CA'
    CHEQUE = 'CH'
    DISCOUNT = 'DI'
    OTHER = 'OT'

    PAYMENT_TYPE_CHOICES = (
        (AUTOPAYMENT, 'Automated Payment'),
        (BANKTRANSFER, 'Bank Transfer'),
        (CASH, 'Cash'),
        (CHEQUE, 'Credit'),
        (DISCOUNT, 'Discount'),
        (OTHER, 'Other'),
    )
    payment_type = models.CharField(max_length=2,
                                    choices=PAYMENT_TYPE_CHOICES,
                                    default=OTHER)
    payment_reference = models.CharField(max_length=10)
    description = models.CharField(max_length=128, null=True, blank=True)
    notes = models.CharField(max_length=128, null=True, blank=True)

class ReferenceMapper(models.Model):
    '''
    Where Payments have been made with the 'wrong' reference
    (that is one which does not exist in an `AccountDebt` model
    instance the `ReferenceMapper` object is used to map the 
    reference that was used to the reference that should have been
    used
    '''

    payment_reference_used = models.CharField(max_length=128)
    payment_reference_intended = models.CharField(max_length=10)
    payment_origination_name = models.CharField(max_length=30)

    def __unicode__(self):
        return unicode(self.payment_reference_used) + " ( Should have been : " + unicode(self.payment_reference_intended) + " )"

membaman/fees/views.py
import datetime

from django.shortcuts import render

from django.views.generic import ListView, DetailView, UpdateView

from django.core.urlresolvers import reverse

from .models import Year, SubYear, Income
from members.models import Member

#TEMP_ORG_NAME = 'Conversion Group'
TEMP_ORG_ID = 71 
TEMP_CURR_YR_START = datetime.date(2015,1,1)
TEMP_CURR_YR_FINISH = datetime.date(2015,12,31)

class IncomeListView(ListView):
    model = Income
    template_name = 'fees/income_list_simple.html'
    context_object_name = "income_list"
    paginate_by = 15

    def __default_yearid(self):
        year_id = self.request.GET.get('year', None)
        if not year_id:
            try:
                obj_year = Year.objects.get(organisation_id=TEMP_ORG_ID, start__lte=datetime.datetime.now(), end__gte=datetime.datetime.now())
            except Year.DoesNotExist:
                lst_year = Year.objects.filter(organisation_id=TEMP_ORG_ID).order_by('start')
                if lst_year:
                    obj_year = lst_year[0]
                else:
                    #If this happens something else is broken
                    raise
            year_id = obj_year.id

        return year_id


    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(IncomeListView, self).get_context_data(**kwargs)
        # Add in a the year that's just been selected to allow us to 
        # to select the correct element of the  the dropdown.
        year_id = self.__default_yearid()
        context['year_id'] = int(year_id)
        return context

    def get_queryset(self):
        '''
        Provide sortation to the QS and add some extra columns
        to contain css class names to allow the template to
        output background colours which enhance the meaning of 
        the data
        '''

        year_id = self.__default_yearid()

        current_subyear_class = 0 
        current_member_class = 0    
        SUBYEAR_CSS_CLASSES = ['syon', 'syoff']
        MEMBER_CSS_CLASSES = ['memon', 'memoff']

        desc_order = False
        qs_income = Income.objects.filter(subyear__year_id=year_id).order_by('member__name_family', 'member__name_given', 'subyear__start', 'subyear__end')
        
        if desc_order:
            qs_income = qs_income.reverse()

        #Setup some flags to drive colour banding in template
        if qs_income:
            current_subyearid = qs_income[0].subyear.id
            current_memberid = qs_income[0].member.id
            for inc in qs_income:
                if inc.subyear.id != current_subyearid:
                    current_subyearid = inc.subyear.id
                    current_subyear_class = 0 if current_subyear_class else 1
                if inc.member.id != current_memberid:
                    current_memberid = inc.member.id
                    current_member_class = 0 if current_member_class else 1

                inc.subyearcssclass = SUBYEAR_CSS_CLASSES[current_subyear_class]
                inc.membercssclass = MEMBER_CSS_CLASSES[current_member_class]

            
        return qs_income

class IncomeListSubYearView(ListView):
    model = Income
    template_name = 'fees/income_list_by_subyear.html'
    context_object_name = "income_list"
    paginate_by = 10

    def get_queryset(self):
        dic_out = {}
        suby_order_list = []
        mem_order_list = []

        qs_subyear = SubYear.objects.filter(year__organisation__pk=TEMP_ORG_ID, start__gte=TEMP_CURR_YR_START, end__lte=TEMP_CURR_YR_FINISH).order_by('start')
        qs_mem = Member.objects.filter(organisation__pk=TEMP_ORG_ID).order_by( 'name_family', 'family__id','name_given')

        for suby in qs_subyear:
            if suby.name not in dic_out:
                dic_out[suby.name] = {}
                suby_order_list.append(suby.name)
            for mem in qs_mem:
                if mem.id not in dic_out[suby.name]:
                    dic_out[suby.name][mem.id] = {}
                    mem_order_list.append(mem.id)

                qs_income = Income.objects.filter(subyear=suby, member=mem).order_by('subyear__start')

                for inc in qs_income:
                    dic_out[suby.name][mem.id] = inc.received 


        return qs_income

membaman/templates/fees/attempt_add.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}


<form method="post" action="">
{% csrf_token %}
    <fieldset>
         <legend>Record your Attempts</legend>
        {{ formset.management_form }}
        {% for form in formset %}
            <p>Can you spell ?:
            <span>{{ form.word.value }}</span>
            <span>
                <label for="{{ form.success.id_for_label }}">Success?:</label> 
                <input id="{{ form.success.id_for_label }}" name="{{ form.success.html_name }}" type="checkbox" />
            </span>
            </p>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Submit Your Results" />
</form>
{% endblock %}

membaman/templates/fees/fees-index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<a href="{% url 'membaman:index' %}">Membaman Home Page</a>|
<a href="{% url 'fees:feesindex' %}">Fees Home Page</a>|
<a href="{% url 'members:membersindex' %}">Members Home Page</a>|
<h2>Fees Home Page</h2>

<ol>
    <li><a href="{% url 'fees:income-list' %}">Income List</a></li>
    <li><a href="{% url 'fees:income-list-subyear' %}">Income List - Subyear</a></li>
    <li><a href="{% url 'membaman:index' %}">Membaman Home Page</a></li>
</ol>

{% endblock %}

membaman/templates/fees/income_list.html
{# .... **Normal content list, maybe a table** .... #}
{% if income_list %}
    <table id="cars">
        {% for car in income_list %}
            <tr>
                <td>{{ car.model }}</td>
                <td>{{ car.year }}</td>
                <td><a href="/car/{{ car.id }}/" class="see_detail">detail</a></td>
            </tr>
        {% endfor %}
    </table>
    {# .... **Now the pagination section** .... #}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/cars?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/cars?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% else %}
    <h3>My Cars</h3>
    <p>No cars found!!! :(</p>
{% endif %}
{# .... **More content, footer, etc.** .... #}

membaman/templates/fees/income_list_by_subyear.html
{% extends "base.html" %}
{% load i18n %}
{% load fees_filter_year_tags %}

{% block content %}

<a href="{% url 'membaman:index' %}">Membaman Home Page</a>|
<a href="{% url 'fees:feesindex' %}">Fees Home Page</a>|

<style>
  table.inctab{
    border-collapse: collapse;
    border: 1px solid black;
  }
  table.inctab td, table.inctab th{
    border: 1px solid black;
    padding: 10px 20px;
  }
  table.inctab td.syon{
    background-color: olive;
  }
  table.inctab td.syoff{
    background-color: green;
  }
  table.inctab td.memon{
    background-color: white;
  }
  table.inctab td.memoff{
    background-color: grey;
  }
  
</style>
<h2>Income</h2>
{% income_year_select_content as income_years %}
<form action="" method="get" accept-charset="utf-8">
    <select name="year" id="year">
        <option value="-1">Select a year</option>
        {% for income_year in income_years %}
            <option value="{{ income_year.id}}">{{ income_year.name }}</option>
        {% endfor %}
    </select>
</form>

{% if income_list %}
    <table class="inctab" id="income">
        <tr>
            <th>Year</th>
            <th>Sub-Year</th>
            <th>Member</th>
            <th>Amount</th>
        </tr>
        {% for income in income_list %}
            <tr>
                <td>{{ income.year_name }}</td>
                <td class = {{ income.subyearcssclass }}>{{ income.subyear_name}}</td>
                <td class = {{ income.membercssclass }}>{{ income.member}}</td>
                <td>{{ income.received }}</td>
            <tr>
        {% endfor %}
    </table>
{% else %}
    <h3>No Income</h3>
    <p>No income found</p>
{% endif %}

{% endblock %}

membaman/templates/fees/income_list_simple.html
{% extends "baselist.html" %}
{% load i18n %}
{% load fees_filter_year_tags %}

{% block content %}

<a href="{% url 'membaman:index' %}">Membaman Home Page</a>|
<a href="{% url 'fees:feesindex' %}">Fees Home Page</a>|

<style>
  table.inctab{
    border-collapse: collapse;
    border: 1px solid black;
  }
  table.inctab td, table.inctab th{
    border: 1px solid black;
    padding: 10px 20px;
  }
  table.inctab td.syon{
    background-color: olive;
  }
  table.inctab td.syoff{
    background-color: green;
  }
  table.inctab td.memon{
    background-color: white;
  }
  table.inctab td.memoff{
    background-color: grey;
  }
  
</style>
<h2>Income</h2>
{% income_year_select_content as income_years %}
<form action="" method="get" accept-charset="utf-8">
    <select name="year" id="year" onchange="this.form.submit()">
        {% for income_year in income_years %}
            {% if year_id == income_year.id %}
                <option value="{{ income_year.id}}" selected="selected">{{ income_year.name }}</option>
            {% else %}
                <option value="{{ income_year.id}}">{{ income_year.name }}</option>
            {% endif %}
        {% endfor %}
    </select>
</form>

{% if income_list %}
    <table class="inctab" id="income">
        <tr>
            <th>Year</th>
            <th>Sub-Year</th>
            <th>Member</th>
            <th>Amount</th>
        </tr>
        {% for income in income_list %}
            <tr>
                <td>{{ income.year_name }}</td>
                <td class = {{ income.subyearcssclass }}>{{ income.subyear_name}}</td>
                <td class = {{ income.membercssclass }}>{{ income.member}}</td>
                <td>{{ income.received }}</td>
            <tr>
        {% endfor %}
    </table>
{% else %}
    <h3>No Income</h3>
    <p>No income found</p>
{% endif %}

{% endblock %}